### ISSUE TITLE
Support Enumerable for Redix

### ISSUE THREAD

**Issue by eppdot** [christhekeele/mnemonix#35]
It would be really nice to have support for Enumerable for `Redix` as one could use the redis command `KEYS {PATTERN}` for that. Furthermore it would be awesome, if one could provide a pattern to the `keys/1` function. For example, when I share Redis with another application/instance I want to only list keys with a scoped suffix like `key:its_this_app`.

**Comment by christhekeele** [comment]
How would you imagine the pattern API working, out of curiosity? It would have to be an addition beyond the standard `Map` functions, I imagine.

I've had an idea in mind for a while to support namespacing (#16) but I feel as if you want to vary the prefix dynamically, per call, rather than at the store level?

**Comment by christhekeele** [comment]
This has been implemented for the next release.
